### ISSUE TITLE
English read me?

### ISSUE THREAD

**Issue by ignatandrei** [Antelcat/AutoGen#1]
I do maintain an opinionated list of Roslyn Code Generators at https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG 

Could you make a readme in English , please? That way I will understand better what it does

**Comment by feast107** [comment]
I m sorry for noticing your issue so late. I will add a README in English as soon as possible.

**Comment by ignatandrei** [comment]
thanks for documentation. I will try to make an example
