### ISSUE TITLE
Does not find GenerateMap ?

### ISSUE THREAD

**Issue by ignatandrei** [Antelcat/AutoGen#2]
Please see attached project. The  attribute 
[GenerateMap]
is not found. Could you please advise?
[mapperDemo.zip](https://github.com/Antelcat/AutoGen/files/14398106/mapperDemo.zip)

**Comment by feast107** [comment]
I'm afraid I forgot to update the sample pic.[GenerateMap] was renamed as [AutoMap] before the first pre-release.

**Comment by ignatandrei** [comment]
THanks
https://ignatandrei.github.io/RSCG_Examples/v2/docs/AutoGen
